version: '3'
services:
  web:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7790:7790"
    command: >
      bash -c "npm install && npm start"
    restart: always
