name: CICD

on:
  push:
    branches: [github-actions]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app .
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Install SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} 'bash -s' << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/admin-wf:latest
            docker stop admin-wf-container || true
            docker rm admin-wf-container || true
            docker run -d -p 7790:7790 --name admin-wf-container ${{ secrets.DOCKER_USERNAME }}/admin-wf
          EOF